name: ml-project-template
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.2
  - matplotlib=3.9.0
  - seaborn=0.12.2
  - pip
  - pip:
      - streamlit==1.26.0
      - mlflow==2.9.1
      - fastapi==0.111.1
      - uvicorn==0.23.2
      - joblib==1.3.2
      - xgboost==1.7.6
      - lightgbm==4.4.2
      - plotly==5.18.0

